branches:
 only:
  - master
  - release

version: "0.0.1.{build}"

install:

  - python -m pip install cookiecutter
  - cookiecutter --no-input .
  - cd ITKModuleTemplate
  - curl -L https://rawgit.com/InsightSoftwareConsortium/ITKPythonPackage/master/scripts/windows-download-cache-and-build-module-wheels.ps1 -O
  - ps: .\windows-download-cache-and-build-module-wheels.ps1

build: off

test: off

artifacts:

  # pushing entire folder as a zip archive
  - path: dist\*

deploy: off
